server:
  port: 8083

spring:
  application:
    name: post-service
  datasource:
    url: jdbc:mysql://localhost:3306/court_monitor?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        enabled: false
    compatibility-verifier:
      enabled: false

mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.example.post.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
